spring.application.name=project02
server.address==0.0.0.0
server.port=8080

# H2 Console (Optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settins.web-allow-others=true

# Datasource Configuration
spring.datasource.url=jdbc:h2:tcp://h2-db:1521/./data/fraude_db;IFEXISTS=FALSE;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Container kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer